# Site settings
# in the templates available like {{ site.myvariable }}.
title: Charles L. Thomas Portfolio Site.
email: cleroythomas@gmail.com
brand: Charles Thomas
headline: Urban Planner, GIS Expert, Web Developer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cityplanningtech.com/" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 319162

# Contacts
email: cleroythomas@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

