# Site settings
# in the templates available like {{ site.myvariable }}.
title: Charles L. Thomas Portfolio Site.
email: cleroythomas@gmail.com
brand: Charles Thomas
headline: Urban Planner, GIS Expert, Web Developer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cityplanningtech.com/" # the base hostname & protocol for your site
copyright: cityplanningtech.com, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 319220

# Contacts
email: cleroythomas@gmail.com
phone: (404) 926-6235

# Tracking
googleAnalitycsID: UA-90673779-1

